const levelsArray = [
//  [
// 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
// 'x                            x',
// 'x                            x',
// 'x                            x',
// 'x                            x',
// 'x                            x',
// 'x                            x',
// 'x                            x',
// 'x                            x',
// 'x                            x',
// 'x       o            o       x',
// 'x                            x',
// 'x                            x',
// 'x            xxx             x',
// 'x       o    x x     o       x',
// 'x            xxx             x',
// 'x                            x',
// 'x       o            o       x',
// 'x                            x',
// 'x                            x',
// 'x                            x',
// 'x                            x',
// 'x                            x',
// 'x             o              x',
// 'x                            x',
// 'x                            x',
// 'x             o              x',
// 'x                            x',
// 'x                            x',
// 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
// ],


[[
'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
'x                            x',
'x    o                  o    x',
'x                            x',
'x                            x',
'x                            x',
'x             o              x',
'x                            x',
'x                            x',
'x                            x',
'x     R              D       x',
'x             o              x',
'x                            x',
'x            xxx             x',
'x            x x             x',
'x            xxx             x',
'x                            x',
'x             o              x',
'x                            x',
'x                            x',
'x     U              l       x',
'x                            x',
'x             o              x',
'x                            x',
'x                            x',
'x                            x',
'x     o        o       o     x',
'x                            x',
'x                            x',
'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
]],



 [[
'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
'x                                         x',
'x                                         x',
'x           R                             x',
'x                                         x',
'x                                         x',
'x                                         x',
'x                   xxxxxxxxxxx      D    x',
'x                   x                     x',
'x          o    o   x    o    o           x',
'x                   x                     x',
'x   U      o    o   x    o    o           x',
'x                   x                     x',
'x                   x                     x',
'x          xxxxxxxxxx                     x',
'x                                         x',
'x                                         x',
'x                       L                 x',
'x                                         x',
'x                                         x',
'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
]],


 [[
'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
'x                                         x',
'x                                    L    x',
'x     R                                   x',
'x                                         x',
'x  x  x  x  x  x  x  x  x  x  x  x  x  x  x',
'x                                         x',
'x    o         o              o      o    x',
'x                                         x',
'x  x  x  x  x  x  x  x  x  x  x  x  x  x  x',
'x                                         x',
'x    o         o                      o   x',
'x                                         x',
'x  x  x  x  x  x  x  x  x  x  x  x  x  x  x',
'x                                         x',
'x                                         x',
'x     R                                   x',
'x                                         x',
'x                                         x',
'x                                   L     x',
'x                                         x',
'x                                         x',
'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
]],



];

const levelsSequence = (function*(levels) {
  for (let i = 0; i < levels.length; i++) {
    yield levels[i];
  }
})(levelsArray)

module.exports = {
  levelsArray,
  levelsSequence,
}
