const map = [
'                              ',
'       xxxxxxxxx              ',
'                              ',
'                              ',
'                              ',
'                              ',
'                              ',
'                              ',
'                              ',
'      o                       ',
'                              ',
'                              ',
'                              ',
'               x              ',
'               x              ',
'               x              ',
'                              ',
'                              ',
'                              ',
'      xxxxxxxxxxxxx           ',
'                              ',
'         x                    ',
'               x              ',
'         o     x              ',
'                              ',
'                              ',
'                              ',
'                          o   ',
'                              ',
'          xxxxxxxx            ',
];

module.exports = {
  map
};